# Generated by Django 4.2 on 2023-11-20 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.user')),
            ],
            options={
                'verbose_name': 'Сообщение пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
    ]
