# Generated by Django 4.2 on 2023-11-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя в Телеграмме')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('signed', models.BooleanField(default=False, verbose_name='Наличие подписки')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
